version: '2'

services:
  redis:
    image: 'redis:alpine'
    command: 'redis-server'
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  web:
    build: .
    image: 'natfoster82/simple'
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'

volumes:
  redis: